### PR TITLE
#258 Adding sportchef-ajax to wrap all ajax requests with an auth token

### PR DESCRIPTION
**Pull request by wheresvic**
If any exists :)

---

This change is [Reviewable](https://reviewable.io/reviews/mcpringle/sportchef/281)

### CODE REVIEW

**Comment by madmas** [comment]
👍 looks good

**Comment by McPringle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/main/resources/webapp/sportchef_components/sportchef-ajax/sportchef-ajax.html, line 27 [r1]](https://reviewable.io:443/reviews/mcpringle/sportchef/281#-KLXbYU_KF3Zu2OCSRLP:-KLXbYU_KF3Zu2OCSRLQ:-1943892873) ([raw file](https://github.com/mcpringle/sportchef/blob/9b2f97860a057febd24c1de6124b2a3c31ad42c0/src/main/resources/webapp/sportchef_components/sportchef-ajax/sportchef-ajax.html#L27)):_

> ``` HTML
> 
>     <script>
>         // register a new element called sportchef-events
> ```

Should be "sportchef-ajax" instead of "sportchef-events", I think… ;-)

---

_[src/main/resources/webapp/sportchef_components/sportchef-ajax/sportchef-ajax.html, line 54 [r1]](https://reviewable.io:443/reviews/mcpringle/sportchef/281#-KLXbsumrIjUzJ1f-CV3:-KLXbsumrIjUzJ1f-CV4:1991930688) ([raw file](https://github.com/mcpringle/sportchef/blob/9b2f97860a057febd24c1de6124b2a3c31ad42c0/src/main/resources/webapp/sportchef_components/sportchef-ajax/sportchef-ajax.html#L54)):_

> ``` HTML
>                 contentType: {
>                     type: String,
>                     value: null // "application/json" for auto json encoding
> ```

It would be great to specify "application/json" as default value instead of "null"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mcpringle/sportchef/281)_

**Comment by wheresvic** [comment]
Done with required changes :)

**Comment by McPringle** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mcpringle/sportchef/281#-:-KL_OnJNLk3yTb9nznmb:1417088721)_

**Comment by McPringle** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mcpringle/sportchef/281)_

**Pull request merged**
